= WebCmsModule
Arne Vandamme, Raf Ceuls
0.0.2-SNAPSHOT
include::variables.adoc[]
[subs=+macros]

----
Copyright (C) 2014-2017 +
Copies of this document may be made for your own use and for distribution to others, provided that you do not charge any fee for such copies and further provided that each copy contains this Copyright Notice, whether distributed in print or electronically.
----

[abstract]
== About
{module-name} aims to provide some core Web CMS features for your Across application out-of-the-box.
Building a simple website is very easy and requires very little development.

Features provided by {module-name} include:

* an extensible link:chap-asset-model.html[Domain Model] with common asset types like link:pages/chap-web-page.html[web pages], link:publication/chap-publication-model.html[articles] and link:chap-redirects.html[redirects] <<Redirects-overview,redirects>>
* a way to manage the link:urls/chap-endpoint-url.html[URLs for these assets].
* a link:content/components/chap-web-components.html[powerful component model] for building templates and managing dynamic content.
* an easy way to link:content/importing/chap-importing-data.html[import data using YAML files]

A fully functional administration UI is available using AdminWebModule and EntityModule.

Module website: {module-url}
