include::variables.adoc[]

[[Redirects-overview]]
= Redirects
Redirects offer you a way to specify one or more request paths that should be redirected to another path or an external url.
A redirect has a destination URL and one ore more paths that should redirect to the destination.
A specific HTTP status code can be configured for every path.

In the domain model, a redirect is implemented as `WebCmsRemoteEndpoint`.
The different paths are the `WebCmsUrl` members of the endpoint (property `urls`).

[[Redirect-import]]
== Importing a redirect
One can import a redirect and its associated urls by using the import infrastructure provided by the import functionality of WebCms.
[source,yaml]
----
assets:
 page:
  /my-page:
    title: My page
    wcm:urls: // <1>
      /an-url: 200 // <2>
      /another-url: 301 
----
<1> The element `wcm:urls` indicates that the next item is going to be one (or many) `WebCmsUrls`.
<2> imports an url by defining it's canonicalpath and the http status code.

[source,yaml]
----
assets:
 page:
  /my-page:
    title: My page
    wcm:urls:
      - path: an-url
        httpStatus: 200 
      - path= another-url
        httpStatus: 301
----
