include::../variables.adoc[]
= Web components

[[overview]]
== Web component model
Web CMS Components are the building block of the pages that are displayed for the end user. Support is provided for a user friendly way of manipulating the content of those components via the back end.

=== WebCmsComponentType

=== WebCmsComponent

`WebCmsComponent`

persisted entity

== WebCmsComponentModel
`WebCmsComponentModelService` and `WebCmsComponentModel`
`WebCmsComponentType`

The persisted entity is implemented by `WebCmsComponent`, but usually you will want to work with the `WebCmsComponentModel`.
The latter represents the entire strongly typed model ready for rendering, whereas the former only has the raw attributes.

converted to a `WebCmsComponent` by a `WebCmsComponentModelWriter`
converted from a `WebCmsComponent` by a `WebCmsComponentModelReader`

include::chap-web-components-base-types.adoc[]

== Activating component support
Any `WebCmsObject` - this includes all assets and components themselves - can have web components linked to it.
Enabling components for WebCmsObject implementations: wire WebCmsObjectComponentViewsConfiguration: registerComponentsAssociation

== Filtering selectable WebCmsComponentType options
To filter the dropdown options for a WebCmsComponent, the user can perform two actions. These two options are provided by the `DefaultAllowedCompontTypeFetcher`. Should you like to provide your own logic to filter the selectable options, for one or more types, you'd have to provide your own implementations of the `WebCmsAllowedComponentTypeFetcher` interface.

=== Non-selectable WebCmsComponentTypes
To prevent a `WebCmsComponentType` from showing up in the list unless explicitly specified, the user has to provide the component type with the `componentRestricted` attribute, with its value set to true. This ensures that unless the WebCmsComponentType is specified as an option for the `WebCmsObject` through a `WebCmsTypeSpecifierLink`, it will never be shown as an option.

Examples of non-selectable WebCmsComponentTypes are the default placeholder, proxy and fixed-container component types.


Example
[source, yaml]
----
types:
  component:
    fixed-container:
      objectId: "wcm:type:component:fixed-container"
      name: Fixed container
      description: Container of a fixed set of components.
      attributes:
        type: fixed-container
        componentRestricted: true
----
- A _fixed-container_ should never be available as a selectable option unless specified (through a WebCmsTypeSpecifierLink) 

=== Selectable WebCmsComponenTypes
In the case where a component type may only contain other specific component types, the type should be provided by the `childComponentsRestricted` attribute, with its value set to true. The provided component type options will then be equal to the specified `WebCmsTypeSpecifierLink` links with link type _allowed-component_.

Example
[source, yaml]
----
types:
  component:
    partner-container:
      name: Partners
      attributes:
        type: container
        childComponentsRestricted: true
      wcm:types:
        - typeSpecifier: "wcm:type:component:partner"
          linkType: allowed-component
----
- A _partner-container_ should only contain components of the type _partner_

== Rendering components

=== Creating shared web components
.Shared web components
[options="header", cols="2,1,1,3,1"]
|================
|Name|Type|Mandatory|Description|Default Value
|Component Type|Component Type|Yes|Type of the component, selectable from the list of predefined component types.|None
|Title|String|Yes|The name of the component. Displayed in the admin section.|None
|Name|String|Yes|The unique identifier with which you can approach the component in your Thymeleaf template. Should be unique, and can be auto-generated based on Title|None
|================
=== Using components in your controllers
`WebCmsComponentModelHierarchy`

=== Placeholders
`WebCmsPlaceholderContentModel`

include::chap-web-components-content-markers.adoc[]

include::chap-web-components-thymeleaf.adoc[]

include::chap-web-components-defining-component-types.adoc[]

:numbered:

[[WebCmsComponent-import]]
== Importing components
