= +++ <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 82.9 95.7" width="40" style="margin-right: 10px"><path fill="#3CA873" d="M0 23.9l15.9-9.2 41.5 23.9-16 9.2"></path><path fill="#0093D8" d="M25.5 9.2L41.4 0l41.5 23.9-16 9.2"></path><path fill="#53DD99" d="M41.4 95.7l16-9.3V38.6l-16 9.2"></path><path fill="#22CEFA" d="M66.9 80.9l16-9.2V23.9l-16 9.2"></path><path fill="#257A50" d="M12.5 64.5L28.9 55l-16.4-9.4"></path><path fill="#4DBC86" d="M12.5 64.5L28.9 74V55"></path></svg> +++ Across - WebCmsModule

include::variables.adoc[]

include::../ax-docs-shared/copyright.adoc[]

---

//== Version
//
//[{{ book.moduleVersion }}](/docs/whats-new.md)
//
//== Authors
//
//Arne Vandamme, Raf Ceuls, Steven Gentens

//== About

WebCmsModule aims to provide some core Web CMS features for your Across application out-of-the-box.
Building a simple website is very easy and requires very little development.

Features provided by WebCmsModule include:

* an extensible [Domain Model](/docs/chap-domain-model.adoc) with common asset types like [pages](/docs/pages/chap-web-page.adoc), [articles](/docs/publication/chap-publication-model.adoc) and [redirects](/docs/chap-redirects.adoc)
* a way to manage the [URLs for these assets](/docs/urls/chap-endpoint-url.adoc)
* a [powerful component model](/docs/components/chap-web-components.adoc#overview) for building templates and managing dynamic content
* an easy way to [import data using YAML files](/docs/importing/chap-importing-data.adoc#importing-data-yaml)

A fully functional administration UI is available using AdminWebModule and EntityModule.


The reference documentation is split up into several parts:

* <<whats-new.adoc#whats-new, What's new in this version>> lists the release notes of WebCmsModule
* <<general-information.adoc#general-information, Getting started>> explains how to start using WebCmsModule
* <<components.adoc#web-components,Web Components>> talk about the fundamentals of how to use web components
* <<importing-data.adoc#importing-data,Importing data>> explains the fundamentals of importing data.
* <<performance-tuning.adoc#performance-tuning,Performance tuning>> provides information on how to improve general performance when using WebCmsModule.
* <<appendix.adoc#appendices,Appendices>>
* <<how-tos.adoc#how-tos,How-tos>> provides a different approach to learning Across through some general tutorials

Module website: {{ book.moduleUrl }}

'''
.About the reference documentation
This document is generated from a {git-across-docs}[separate Github repository] using Asciidoctor.

Corrections, additions and general contributions to this documentation are very welcome and can be submitted through the source code repository.



